version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/
    overwrite: yes
file_exists_behavior: OVERWRITE

#permissions: # CodeDeploy에서 EC2서버로 넘겨준 파일들을 모두 ec2-user권한을 갖도록 합니다.
# - object: /
#   pattern: "**"
#   owner: ec2-user
#   group: ec2-user

# ApplicationStart 단계에서 deploy.sh를 실행시키도록 합니다.
hooks: # CodeDeploy배포 단계에서 실행할 명령어를 지정합니다.
  ApplicationStart: # deploy.sh를 root권한으로 실행합니다.
    - location: deploy.sh
      timeout: 300 # 스크립트 실행 300초 이상 수행되면 실패가 됩니다.
      runas: root